language: cpp
os: linux
arch:
  - amd64
  - ppc64le
compiler:
  - gcc
git:
  strategy: clone
  depth: 1
  submodules: true
  submodules_depth: 1
script:
  - cd tests
  - g++ -isystem../rapidcheck/include -I../include -L../rapidcheck -I../include Main.cpp -lrapicheck
  - ./a.out
