language: cpp

os: linux

arch:
  - amd64
  - ppc64le

compiler:
  - gcc

matrix:
  allow_failures:
    - arch: ppc64le

git:
  strategy: clone
  depth: 1
  submodules: true
  submodules_depth: 1

script:
  - cd rapidcheck
  - cmake .
  - make -j8
  - cd ../tests
  - g++ --std=c++11 -Wall -isystem../rapidcheck/include -I../include -L../rapidcheck -I../include Main.cpp -lrapidcheck
  - ./a.out
