remote_theme: tsmanner/just-the-docs

aux_links:
  "GitHub":
    - "https://github.com/tsmanner/parity"

collections:
  unstable:
    permalink: "/:collection/docs/:name/"
    output: true
  v1.0.1:
    permalink: "/:collection/docs/:name/"
    output: true
  v1.0.0:
    permalink: "/:collection/docs/:name/"
    output: true

just_the_docs:
  collections:
    unstable:
      name: Latest
    v1.0.1:
      name: v1.0.1
